"""
OS-RL data-refresh module.

Periodically replaces a subset of the trajectory pool with fresh rollouts
generated by the *current* LoRA policy.  This keeps the offline GRPO
training from staling on fixed data while avoiding the cost of fully
online rollout.

Usage (called from osrl_offline_train.py):
    from exps_research.rl.osrl_collect import refresh_data_pool
    refresh_data_pool(policy, tokenizer, questions_pool, grouped,
                      n_questions=30, n_seeds=2, device=device, args=args,
                      logger=logger)
"""

from __future__ import annotations

import logging
import random
import time
from typing import Dict, List, Optional, Tuple

import torch

logger_default = logging.getLogger("osrl_collect")

# --------------------------------------------------------------------------- #
# Math scoring helpers (same as used in AgentDistill's original pipeline)
# --------------------------------------------------------------------------- #

def _score_answer(generated: str, true_answer: str) -> bool:
    """
    Return True if `generated` matches `true_answer` as a math answer.
    Falls back to case-insensitive exact match if the math grader is unavailable.
    """
    try:
        from exps_research.unified_framework.math_utils.qwen_math_parser import extract_answer
        from exps_research.unified_framework.math_utils.qwen_math_grader import math_equal
        pred = extract_answer(str(generated), data_name="math")
        ref  = extract_answer(str(true_answer), data_name="math")
        return bool(math_equal(pred, ref))
    except Exception:
        pass
    # Fallback: exact match after stripping
    return str(generated).strip().lower() == str(true_answer).strip().lower()


# --------------------------------------------------------------------------- #
# Smolagents model wrapper around the loaded PeftModel
# --------------------------------------------------------------------------- #

class PolicyWrapperModel:
    """
    Thin wrapper that makes a loaded HF/PEFT model behave like a smolagents
    Model so it can be passed to CodeAgent.

    The wrapper is intentionally minimal: it only implements `__call__`
    (which CodeAgent uses for generation) and exposes `model_id` (used in
    log_data metadata).
    """

    def __init__(
        self,
        peft_model,
        tokenizer,
        device: torch.device,
        temperature: float = 0.7,
        max_new_tokens: int = 1024,
    ) -> None:
        self._model = peft_model
        self.tokenizer = tokenizer
        self.device = device
        self.temperature = temperature
        self.max_new_tokens = max_new_tokens
        self.model_id = "policy_lora"
        # smolagents uses these to track cost; set to 0 (no API calls).
        self.last_input_token_count  = 0
        self.last_output_token_count = 0
        # CodeAgent checks flatten_messages_as_text on the model.
        self.flatten_messages_as_text = True

    # ------------------------------------------------------------------
    def __call__(
        self,
        messages,
        stop_sequences: Optional[List[str]] = None,
        grammar=None,
        tools_to_call_from=None,
        **kwargs,
    ):
        """
        Generate a response for `messages` using the current policy.

        `messages` is a list of dicts ({"role": ..., "content": ...}).
        Returns a smolagents ChatMessage-compatible object.
        """
        from smolagents.models import ChatMessage, MessageRole

        # Flatten smolagents message content (may be list-of-dicts or str)
        flat_msgs = []
        for m in messages:
            content = m.get("content", "")
            if isinstance(content, list):
                content = "".join(
                    c.get("text", "") if isinstance(c, dict) else str(c)
                    for c in content
                )
            flat_msgs.append({"role": m["role"], "content": str(content)})

        # Tokenise with the HF chat template
        try:
            inputs = self.tokenizer.apply_chat_template(
                flat_msgs,
                tokenize=True,
                add_generation_prompt=True,
                return_tensors="pt",
            )
            if hasattr(inputs, "keys"):
                input_ids = inputs["input_ids"].to(self.device)
            else:
                input_ids = inputs.to(self.device)
        except Exception as exc:
            logger_default.warning(f"[collect] apply_chat_template failed: {exc}")
            return ChatMessage(role=MessageRole.ASSISTANT, content="")

        prompt_len = input_ids.shape[1]

        # Build stop token ids if stop_sequences are given
        stop_token_ids: Optional[List[int]] = None
        if stop_sequences:
            stop_token_ids = []
            for seq in stop_sequences:
                ids = self.tokenizer.encode(seq, add_special_tokens=False)
                if ids:
                    stop_token_ids.append(ids[-1])

        gen_kwargs: Dict = dict(
            input_ids=input_ids,
            max_new_tokens=self.max_new_tokens,
            do_sample=True,
            temperature=self.temperature,
            pad_token_id=self.tokenizer.eos_token_id,
            use_cache=False,  # gradient_checkpointing is still active; skip kv-cache
        )
        if stop_token_ids:
            gen_kwargs["eos_token_id"] = stop_token_ids

        with torch.no_grad():
            out = self._model.generate(**gen_kwargs)

        generated_ids = out[0, prompt_len:]
        output_text = self.tokenizer.decode(generated_ids, skip_special_tokens=True)

        # Truncate at stop sequences if any remain in the text
        if stop_sequences:
            for seq in stop_sequences:
                idx = output_text.find(seq)
                if idx != -1:
                    output_text = output_text[: idx + len(seq)]

        self.last_input_token_count  = prompt_len
        self.last_output_token_count = len(generated_ids)

        return ChatMessage(role=MessageRole.ASSISTANT, content=output_text)


# --------------------------------------------------------------------------- #
# Single episode
# --------------------------------------------------------------------------- #

def run_agent_episode(
    policy,
    tokenizer,
    question: str,
    true_answer: str,
    device: torch.device,
    max_steps: int = 5,
    temperature: float = 0.7,
    max_new_tokens: int = 1024,
    log: logging.Logger = logger_default,
) -> Optional[Dict]:
    """
    Run one full agent episode using `policy` on `question`.

    Returns a trajectory dict compatible with the training data format:
        {
            "question":          str,
            "generated_answer":  str,
            "true_answer":       str,
            "is_correct":        bool,
            "log_data":          dict,   # contains "messages" list
        }
    or None on failure.
    """
    try:
        from smolagents import CodeAgent
    except ImportError:
        log.error("[collect] smolagents not importable; skipping episode.")
        return None

    instruction = (
        "\n\nIMPORTANT: Always provide a 'Thought:' sequence, and a "
        "'Code:\n```py' sequence ending with '```<end_code>' sequence, "
        "else you will fail. For math problems that are not multiple-choice, "
        "always output the final answer using LaTeX \\boxed{} format. "
        "Provide the exact value (e.g., \\boxed{\\frac{9}{14}}), not a "
        "decimal approximation (e.g., \\boxed{0.642857})."
    )

    sm_model = PolicyWrapperModel(
        peft_model=policy,
        tokenizer=tokenizer,
        device=device,
        temperature=temperature,
        max_new_tokens=max_new_tokens,
    )

    agent = CodeAgent(
        tools=[],
        model=sm_model,
        additional_authorized_imports=["numpy", "sympy", "numpy.linalg"],
        verbosity_level=0,
        max_steps=max_steps,
        set_timeout=True,
    )

    try:
        result, log_data = agent.run(
            question + instruction,
            return_log_data=True,
        )
    except Exception as exc:
        log.debug(f"[collect] agent.run failed: {exc}")
        return None

    is_correct = _score_answer(str(result or ""), str(true_answer))
    return {
        "question":         question,
        "generated_answer": str(result or ""),
        "true_answer":      true_answer,
        "is_correct":       is_correct,
        "log_data":         log_data,
    }


# --------------------------------------------------------------------------- #
# Batch refresh
# --------------------------------------------------------------------------- #

def refresh_data_pool(
    policy,
    tokenizer,
    questions_pool: List[Tuple[str, str]],   # [(question, true_answer), ...]
    grouped: Dict[str, List[Dict]],
    n_questions: int,
    n_seeds: int,
    device: torch.device,
    max_steps: int = 5,
    temperature: float = 0.7,
    max_new_tokens: int = 1024,
    log: logging.Logger = logger_default,
) -> int:
    """
    Generate `n_seeds` new trajectories for each of `n_questions` randomly
    sampled questions, then merge them into `grouped` (replacing old entries
    for those questions).

    The policy is set to eval() mode during collection and restored to
    train() mode afterwards.

    Returns the number of successfully collected trajectories.
    """
    if not questions_pool:
        log.warning("[collect] questions_pool is empty; skipping refresh.")
        return 0

    sample_n = min(n_questions, len(questions_pool))
    sampled = random.sample(questions_pool, sample_n)

    was_training = policy.training
    policy.eval()

    n_collected = 0
    t0 = time.time()

    for q_idx, (question, true_answer) in enumerate(sampled):
        new_trajs: List[Dict] = []
        for seed_i in range(n_seeds):
            traj = run_agent_episode(
                policy=policy,
                tokenizer=tokenizer,
                question=question,
                true_answer=true_answer,
                device=device,
                max_steps=max_steps,
                temperature=temperature,
                max_new_tokens=max_new_tokens,
                log=log,
            )
            if traj is not None:
                new_trajs.append(traj)
                n_collected += 1

        if new_trajs:
            # Replace the oldest entries for this question so the pool
            # stays bounded.  Keep at most len(old) entries total.
            old = grouped.get(question, [])
            max_pool = max(len(old), n_seeds)
            merged = (old + new_trajs)[-max_pool:]
            grouped[question] = merged

        if (q_idx + 1) % 5 == 0 or (q_idx + 1) == sample_n:
            log.info(
                f"[collect] refresh {q_idx+1}/{sample_n} questions done  "
                f"collected={n_collected}  "
                f"t={time.time()-t0:.0f}s"
            )

    if was_training:
        policy.train()

    log.info(
        f"[collect] refresh complete: {n_collected} new trajectories "
        f"across {sample_n} questions  t={time.time()-t0:.0f}s"
    )
    return n_collected
